language: r
pandoc_version: 1.19.2.1

#env:
  #global:
    #- secure: dl3clhQpAUlK83nEwxJMQolWzTq1aMQcJ7N0djuGX4iMsFLTC2+easPj6PoiyZD/H2iPoyNKS+vUeijHlTb5W872ebWx696yLliUUQEhzgLk2zPUeSgucs2dRJsV3YXec27Qwy1IapGTGa/L3RWqBZ58znGhgrJYwcZ/PutwjFUkuiU/XlQ3rTY4nJ8WUc3eR7npi8llXBp3ILkbbS3LlYw2xnfMXc48AQH2jDqHO8vmvZKt4CZjgNgq4fzetXz6kg/406YKxw35+d6bM9UIpcZLnkWr9lukjYcdlY/jD+xaqJGdIjB44/iimgKQc+R8nuDk8DIarTFo6ro5iqj2HjdradW5o8SdFbrvPCvX7GkdnGNKROBPY+7tM09ucmLuvV2bHrBRpiBs0999tIKvOwaG7Qs/OJXlRZzo6b9OxJ4p87eWarJvhvKIqWlrHd3lZyc4fKjc3q4W2MKkFfYL5dLNWdwleWiWg5UJlaC5Xsha6sAVZVUc/BS7BU0C30QCFZ4p4BZ5QEY90+Ew2K/O1oBY7qU2QQOeWZ7dOSvlq2ASjU+gSWl2aLZbGN9SC/GFppokKbUwrZboH0JOddwshhAwugr9PsS4FjC+eFs+X97tnQnuvZmGk7hR+6RV1/HOc5ifwKgScWINNe4AaFXySMgY3auY96EGlxwxD/3wpNI=
    

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  #- _deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master
