language: r
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "QnW8p2nAKqn7UGn2p99VcdkPu7/4P/mfWbpEL+ED2JbrUnwSWCPMn0IDDrH3VH1J63yZA1S0IV06OAEWdDpZhATSh4UOfBIAvh3vL7n1zFVnwwn0GM4BIw2UINph5zEBNHA1vPSCFG8DYLxlGCwajAaGTN9ZjRQFAzgejNJ/faHWwo6N6C2uLcgrX+i332K37Abh6+y/8Xe52IqES5HoJePTITHBY1Zv1LP9Cwx/NNoS9UckD2vTfcuoPB9Oku3ZGNJnhdWym8n3IwUcBdmdqlSFtRyloeQzz3TptJXLnHllDpCe3hZXFv2FjFYRf8asGqk9RkgD5fZ10iMyIjY866B5IRntryMYf/8W/+1M2W3ZB7X6DqQ32Cm7ixOaoEalpFl0weV1xv6RoxEDZLe1dbjAg4eAVqqdBGuAq6gKjtyAIpPtlOcXMi5JdXnF4S0wsJG2NLkB/cRiss8rgDdIB2o6u5XoiNX/Ebb/N1vsA7eKc3od3H707muTIaezKGEkEzv3WeKzSMnLdWWlxJkKADm8hxYmR2FDLDQKe8Vd50nlHI24OrhukVBENXrZSu50JOcjgQc7LBW9ivXynShmGCRSP7q5oebHhxXQt1gc9lPI0qXNqkeRowbh0xycW7qiO7gfYP9AEb5wotZVylriTaWP5BmAhsKsS86IVRraPNw="
    
script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  #- _deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: GITHUB_PAT  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master
