language: r
pandoc_version: 1.19.2.1
    
script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  #- _deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master
