language: r
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "LYujVidjmFseBEnC6yhuKu+PTyb4FhoqHQtkUfnEhq27Jc730hn83B2WOeRuzm0Q5lTz+IEgCbjnd0335icqsfk38ybcolgkQnuqtWjGxWQiL9/oBhI2j51eWCvEVZ72LU4s8xL7Wn2gWia6LAynNCqM4R1GwvvIk1FpIpQbkehjDHVr568ZneKaZAcySboemMmSP1IGe7ApwblMVR2WQxnsFJy2ZbwTpkkQshPYLxAkHaOMXWPrsn71Nr2LgfToC95P9fQZ2X2nG7n+NuBgl+9z9M/JRvxkuPA2+Kq9/ARZFSomQqxiHn2VT/qlPA+m2yOOAk4+InaN7Z88ljd32MmcYv36f1YXOH3mR/6ssGgHmZ+7Pt7fTA2cRnynDZYTWmoXg+9QxppjCySJKnNOdf5TbDblISPenV03izGYnRYgZXz4qhYS7bmUEtbvE//1GLNQ8rtonD1MKms05vOLCNfUyhBsNPwNqvfDne9DaITJZV5iBAEoeougXvz7jqpTc2BTaavw46R0oHEBPn/eXeB8uV0WFpyU/Jbh6w73rNyn8aMG+SVSG/9q5ZHTrZw6TD61GIoAO6x1CKUMcSI+TxEbX+ZD5hhHmYFIoJty/Xmsjwe4Y7SasJJi8hDV8Jz1mRhvgJeB9QQe/V/eFCYtIMSBKnEvUFcIe0UWw7CIVAs="
    

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  #- _deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: GITHUB_PAT  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master
