language: r
pandoc_version: 1.19.2.1

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  - _deploy.sh

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files



